# Backstage override configuration for your local development environment
backend:
  database:
    connection:
      host: localhost
      # Default postgresql port is 5432; this might be different for your installation
      port: 5432
      user: postgres
      # Replace the password below with your postgresql password:
      password: secret